train: C:/Users/surab/PycharmProjects/LNPR/train
val: C:/Users/surab/PycharmProjects/LNPR/valid
test: C:/Users/surab/PycharmProjects/LNPR/test

nc: 1
names: ['License_Plate']

roboflow:
  workspace: roboflow-universe-projects
  project: license-plate-recognition-rxg4e
  version: 4
  license: CC BY 4.0
  url: https://universe.roboflow.com/roboflow-universe-projects/license-plate-recognition-rxg4e/dataset/4